# stdlib
import atexit
from multiprocessing import set_start_method
import os
import shutil
import socket
import sys
import time

# syft relative
from ..grid.duet.process_test import SyftTestProcess

set_start_method("spawn", force=True)


def cleanup() -> None:
    checkpoint_dir = "checkpoints"
    try:
        shutil.rmtree(checkpoint_dir)
    except BaseException:
        pass
    try:
        os.makedirs(checkpoint_dir, exist_ok=True)
    except BaseException:
        pass

atexit.register(cleanup)


def do() -> None:
    # stdlib
    import time

    # syft absolute
    import syft as sy

    sy.logger.add(sys.stderr, "ERROR")

    start = time.time()

    # syft relative
    from . import (  # noqa: F401
        {{DO_SCRIPT}},
    )

    sys.stderr.write(f"DO sending took {time.time() - start} sec\n")

    sy.core.common.event_loop.loop.run_forever()


def ds() -> None:
    # stdlib
    import time

    # syft absolute
    import syft as sy

    sy.logger.add(sys.stderr, "ERROR")
    start = time.time()

    # syft relative
    from . import (  # noqa: F401
        {{DS_SCRIPT}},
    )

    sys.stderr.write(f"DS get took {time.time() - start} sec\n")


{{LIB_DECORATOR}}
def test_{{TESTCASE}}() -> None:
    cleanup()

    start = time.time()

    do_proc = SyftTestProcess(target=do, args=())
    do_proc.start()

    ds_proc = SyftTestProcess(target=ds, args=())
    ds_proc.start()

    ds_proc.join(400)

    do_proc.terminate()

    if do_proc.exception:
        exception, tb = do_proc.exception
        raise Exception(tb) from exception

    if ds_proc.exception:
        exception, tb = ds_proc.exception
        raise Exception(tb) from exception

    if ds_proc.is_alive():
        ds_proc.terminate()
        raise Exception("ds_proc is hanged")

    print(f"test passed in {time.time() - start} seconds")
